# Generated by Django 5.2.7 on 2025-10-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Online disponible'),
        ),
    ]
