# Generated by Django 5.2.7 on 2025-10-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_meal_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock Count'),
        ),
    ]
