# Generated by Django 5.2.7 on 2025-10-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_meal_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='meal_images/default_meal.jpg', upload_to='meal_images', verbose_name='Image du repas'),
        ),
    ]
