# Generated by Django 5.2.7 on 2025-10-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_meal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='meal_images/default_meal.png', upload_to='meal_images', verbose_name='Image du repas'),
        ),
    ]
