# Generated by Django 5.2.7 on 2025-10-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_ordertransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('failed', 'FAILED'), ('completed', 'COMPLETED')], default='Pending', max_length=9, verbose_name='Delivery Status'),
        ),
    ]
